### ISSUE TITLE
adding a task gets no method error

### ISSUE THREAD

**Issue by mikeducey** [mikeducey/to-do-list_OO#2]
I'm experiencing an error when testing out the add-a-task function, named "createNewTask" in task.rb.  Though it's called in the controller, I experience a no method error when the page is redirected to the home page.

What I am doing:
1.  Log onto home page.
2. Click "New task"
3.  Enter in a new task and select a name"
4.  Click submit.

What I expect:  a redirection to the home page, with the new task listed at the bottom of the tasks that are incomplete (to do).  

What happens: an error page, saying that there is a NoMethodError at new/process.   It states there is an undefined method "createNewTask", which is strange, as it is defined in the model!

**Comment by sumeetjain** [comment]
While I look into this further, can you re-rackup and try again? (I assume you've already tried this, but still.)

**Comment by sumeetjain** [comment]
Nevermind, I found the error. I'm not going to tell you what it is, except to suggest that you go character by character through the block below to find the issue. Post here when you've found the problem, please :)

``` ruby
MyApp.post "/new/process" do

    @newtask = Task.new(params[:person], params[:task])
    addTask = @newTask.createNewTask
    redirect '/'
end
```
