### ISSUE TITLE
No implicit conversion of string to integer

### ISSUE THREAD

**Issue by mikeducey** [mikeducey/to-do-list_OO#4]
![string to integer](https://cloud.githubusercontent.com/assets/19538441/17370771/f8849972-5962-11e6-804d-abd37c7ac6ed.png)

test_save is failing, because of a no implicit conversion of string to integer error that I get when running the test.  (Image of error message is posted here).  Based on the error message, I'm inferring something is wrong with the method itself.  The issue seems to come from line 26 in the tasks.rb file., which states:
`Task.new(@id, newTask["task"], newTask["name"], newTask["status"])`

So, it's not liking the new object that I'm creating.  I'm just not sure as of now what string is being converted to an integer.  I've tried removing quotes, adding quotes, etc. to just about every part of that new object, to no avail.  

I'm sure I'm missing something simple, but what item is attempting to convert from a string to error, and why?  And why is that problematic?  I create a new object (a la Task.new) for another method in almost the same way without an issue (the only difference being the `@id.`  Is that what is causing the issue?

**Comment by sumeetjain** [comment]
Usually this means that you're trying to access a _named key_ (like `"task"`) for something that is not actually a Hash but rather is an Array. The error is saying, "Ruby knows how to get values in this collection based on an Integer index. You're giving us a String though. We can't convert Strings to Integers. We're not _magic_."

Use a `binding.pry` to figure out where you've gone wrong. Reach out again in 20 minutes if that isn't fruitful.

**Comment by mikeducey** [comment]
Okay, I think I know what's going on, but I don't know how I should proceed.  It doesn't like the object I'm creating.  In fact, the variable it's trying to get values from with .task and .name is just an empty array.  The variable newTask that is being assigned what is the outcome of the DB.execute is just and empty array.  So I need to restructure what is being returned so that it's an object (or a different kind of object?).  I guess I don't know exactly what to change about either newTask or the new object being created so that it isn't either starting out as an empty array or that the object being created is of a different kind.  Should I, for instance, use my whereID method to call that last line?  Or does that sort of defeat the purpose of the save method (since it's just supposed to update the database with another entry, so that when it's sorted by the other methods it just has the new entry there in addition to the others?  I feel like that if I create a new object here, It could perhaps screw up the sort methods.  Perhaps I don't understand the relation between an object being created here and how it might affect the other methods.  Maybe it won't!

**Comment by sumeetjain** [comment]
> The variable newTask that is being assigned what is the outcome of the DB.execute is just and empty array.
> Yup. You're not asking for any information from SQLite. You're just telling it to create a new row in a table. Your assumption is that SQLite returns back that newly added record after adding it. It does not. The empty array is the intended response from SQLite.

If you want to get the information about that record, you need to use a `SELECT` command. That's how SQL expects to be asked for information.

But if your goal is to get those values simply to populate your object's attributes, you don't even need to go that far. You have the information you need right there in the method! :)

``` ruby
def self.save(task, name)
    newTask = DB.execute("INSERT INTO tasks (task, name, status) VALUES (\"#{task}\", #{name}, 2)")
    @id = DB.last_insert_row_id

    Task.new(@id, newTask["task"], newTask["name"], newTask["status"])
end
```

See? The information you need is right there: `task` and `name` are the values you need. And `2`, which you're hardcoding. Just change your method to:

``` ruby
def self.save(task, name)
    newTask = DB.execute("INSERT INTO tasks (task, name, status) VALUES (\"#{task}\", #{name}, 2)")
    @id = DB.last_insert_row_id

    Task.new(@id, task, name, 2)
end
```

Maybe even better would be:

``` ruby
def self.save(task, name)
        default_status = 2
    newTask = DB.execute("INSERT INTO tasks (task, name, status) VALUES (\"#{task}\", #{name}, #{default_status})")
    @id = DB.last_insert_row_id

    Task.new(@id, task, name, default_status)
end
```

**Comment by mikeducey** [comment]
That's beautiful.  I don't know why I was making it overcomplicated.  I also like the `default_status` variable.  Much more elegant!
