### ISSUE TITLE
What tests can be run on a delete row/record method?

### ISSUE THREAD

**Issue by mikeducey** [mikeducey/to-do-list_OO#5]
I have a method that deletes an entry in the database.  It looks as follows:

`def self.deleteTask(id)
        DB.execute("DELETE from tasks WHERE id == #{id}")
    end`

Simple enough!  What sorts of tests can I run on this function?  The test setup is as follows:

`   def test_deleteTask
        DB.execute("INSERT into tasks (name, task, status) VALUES (1, \"Make Paint\", 2)")
        @last_id = DB.last_insert_row_id

```
    no_task = Task.deleteTask(@last_id)

end`
```

I just don't know what I can check for this!  I can't even do assert_nil, for there is an empty array returned, and not a nil value.  I just am unsure what to check!  

I cannot run a check like `assert_equal(no_task.name, nil)` as it returns an error that reads `undefined method`name' for []:Array`

What sorts of things can I look to check to be asserted or refuted as equal! (or other checks, of course!)

**Comment by halfghaninne** [comment]
If you try to query the DB for a task by its `id` and a task with that id doesn't exist, what kind of return do you get? Can you test against that?
