### ISSUE TITLE
creating object for method when there are many returns from DB

### ISSUE THREAD

**Issue by mikeducey** [mikeducey/to-do-list_OO#6]
Hi!  Lotta help today... I hope that's okay!

I'm writing tests for the method that sorts the DB by status.  The method looks as follows: 
`def self.sort_by_status(status)
        sorted_tasks = DB.execute("SELECT * FROM tasks WHERE status ==#{status}")
        @status = status
    end`

I want to have there be a new object for this method (like seen in the whereID method that makes a new object as follows; 
`Task.new(selectedTask["id"], selectedTask["task"], selectedTask["name"], selectedTask["status"])`

In this case, I'd obviously change `selectedTask` to `sorted_tasks`.  But the idea is that, after the DB.execute, the variable `sorted_tasks` will contain many rows from the DB (as hashes).  If I want to make an object that I can get values from with the attr_reader, how might I make such an object?

Thought:
With whereID, I can just call selectedTask[0], but I don't want to call a specific hash from sorted_tasks.

**Comment by sumeetjain** [comment]
> Hi! Lotta help today... I hope that's okay!

Mike. _Mike._ Please. No more defensiveness about asking questions. :) For our sake, if not for yours, as it makes our job harder if we have to assuage while also instructing. Your relationship with us should be to _expect_ to receive help. I don't apologize to my doctor when I need to visit her for a checkup, and I certainly wouldn't apologize to my lawyer for taking up "their" time.

---

Quick note about typing code into issues on GitHub. You did this:

![](https://cl.ly/grgU/Screen%20Shot%202016-08-03%20at%201.52.43%20PM.png)

You should have done this:

![](https://cl.ly/grVu/Screen%20Shot%202016-08-03%20at%201.53.08%20PM.png)

That maintains the line breaks.

Even better is this, which helps GitHub apply colored syntax highlighting:

![](https://cl.ly/greU/Screen%20Shot%202016-08-03%20at%201.53.44%20PM.png)

Result:

``` ruby
def self.sort_by_status(status)
  sorted_tasks = DB.execute("SELECT * FROM tasks WHERE status ==#{status}")
  @status = status
end
```

---

Answer to your question:

If you get back an array of hashes from the DB, loop through them. Something like this:

```
array_of_objects = []

array_of_hashes_from_db = ...

loop through array_of_hashes_from_db... |x|
    array_of_objects << x
end

return array_of_objects
```

Hopefully I'm understanding you correctly.

**Comment by mikeducey** [comment]
This is great stuff, wish I'd thought of it!

**Comment by mikeducey** [comment]
So, I do like that this returns an array of hashes of the information, but would this count as a new Object?  I know that, for the most part, we want to have a new Class object from our functions (or at least it's specified that way in the method example.  Would the fact that this sort method would return an array of hashes be acceptable in our new format?  Or is there a way to work within that array to make each hash into a Task object like we could get from a method like this:

``` ruby
    def self.whereID(id)
        selectTask = DB.execute("SELECT * FROM tasks WHERE id == #{id}")
        selectedTask = selectTask[0]

        Task.new(selectedTask["id"], selectedTask["task"], selectedTask["name"], selectedTask["status"])
    end
```

Where `Task.new(selectedTask["id"], selectedTask["task"], selectedTask["name"], selectedTask["status"])` allows for the use of things like .name or .status to use those methods specified in the attr reader and writers.  

As is, my current method looks as follows:

``` ruby
    def self.sort_by_status(status)
        array_by_status = []
        @status = status
        sorted_tasks = DB.execute("SELECT * FROM tasks WHERE status ==#{status}")
        sorted_tasks.each do |x|
            array_by_status << x
        end
        return array_by_status

    end
```

Which works well to return the array! Say I were to modify it to create each in such a way that we get new Task objects for each hash, like so:

``` ruby
    def self.sort_by_status(status)
        array_by_status = []
        @status = status
        sorted_tasks = DB.execute("SELECT * FROM tasks WHERE status ==#{status}")
        sorted_tasks.each do |x|
            array_by_status << x
        end

        array_by_status.each do |y|
            Task.new(y["id"], y["task"], y["name"], y[@status])
        end
        return array_by_status

    end
```

Can I work within the array in the way I've written?  My tests that have been run so far seem to suggest that I cannot!

**Comment by sumeetjain** [comment]
You're right. I spaced on my initial reply. My pseudocode should have looked more like this:

```
array_of_objects = []

array_of_hashes_from_db = ...

loop through array_of_hashes_from_db... |x|
    array_of_objects << Task.new(x["id"], x["task"], x["name"], x["status"])
end

return array_of_objects
```

If implementing something like this isn't working for you, ask a new question with the specific error you're encountering.

**Comment by mikeducey** [comment]
I think it works in the way I am looking for it to work!
