### ISSUE TITLE
Feedback on ORM

### ISSUE THREAD

**Issue by halfghaninne** [mikeducey/to-do-list_OO#7]
Mike this is really nice work! I'm going to give some pretty granular feedback, but that's because on the whole, your code is well-written, easy to follow, and well-tested. I'm also hoping that specific feedback will help in illuminating how your modules can be utilized.

First, re: Modules, **think of Modules as a place to refactor work that is duplicated between your Classes.** That being said, your Modules don't have to be unique to a certain Class (right now the one you have is named `TaskORM`).

I view finding and deleting (and potentially even updating attributes) as actions that are generic-enough to be good candidates for being moved to Modules. In moving this work to the Module, you may find that more information needs to be passed to the method.

So, if your Modules are changed a bit to be used for any/all of your Classes (and added to them via `include` or `extend`), your `self.find(id)` method in your Module and your `self.whereID(id)` method in your Task Class will become redundant. Likewise for a couple of other methods in your Classes.

One other piece of low-hanging fruit: I would encourage moving your Classes into their own files, each named after the Class. Your Classes are small (and well-documented!) enough right now that it's not an issue, but moving forward this kind of organization is helpful!

Let me know here or in-person if you have any questions!

**Comment by mikeducey** [comment]
Funny- I did have the second class in a separate file, but then I was thinking of another student's example and they had them all on one page so I deleted it and moved the class to the other class's file.  Too bad, but I'll definitely re-create it!  

I'll get to work on the modules in short order here as well!

Thank you for the feedback.
